name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        cmake_generator: ["Visual Studio 17 2022"]
        cmake_generator_platform: ["Win32","x64"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1

    - name: Configure
      run: cmake -S . -B ../build_folder -G "${{matrix.cmake_generator}}" -A "${{matrix.cmake_generator_platform}}"

    - name: Build
      run: cmake --build ../build_folder --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ../build_folder --build-config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ../build_folder --prefix ${{github.workspace}}/../install_folder --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cmake --build ../build_folder --target package --config ${{env.BUILD_TYPE}}
